# Application name
spring.application.name=practice-atlas

# Server port (default 8080, you can change if needed)
server.port=8080

# MongoDB Atlas connection
spring.mongodb.uri=mongodb+srv://jacksparrow:Jack1221@cluster0.gnltnhm.mongodb.net/amazon_db

# (Optional) Show MongoDB queries in console
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# (Optional) Reduce unnecessary logs
logging.level.org.mongodb.driver=INFO

