/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busbookingmanagement.gui.admin;

import busbookingmanagement.gui.admin.BusDetails;
import busbookingmanagement.gui.user.LoginFrame;
import busbookingmanagement.util.Session;
import javax.swing.JOptionPane;

/**
 *
 * @author guruv
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
         welcomelbl.setText("Welcome " + Session.currentUserName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        welcomelbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        butDetailbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        checkticketsBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel2.setLayout(new java.awt.BorderLayout());

        welcomelbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        welcomelbl.setForeground(new java.awt.Color(0, 0, 153));
        welcomelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomelbl.setText("Welcome Admin");
        jPanel2.add(welcomelbl, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(720, 70));
        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 102), new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(255, 102, 102)));
        jPanel5.setPreferredSize(new java.awt.Dimension(380, 300));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        butDetailbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butDetailbtn.setForeground(new java.awt.Color(102, 0, 102));
        butDetailbtn.setText("Bus Details");
        butDetailbtn.setMargin(new java.awt.Insets(3, 14, 3, 14));
        butDetailbtn.setPreferredSize(new java.awt.Dimension(160, 40));
        butDetailbtn.addActionListener(this::butDetailbtnActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(butDetailbtn, gridBagConstraints);

        logoutbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logoutbtn.setForeground(new java.awt.Color(255, 51, 51));
        logoutbtn.setText("LogOut");
        logoutbtn.setPreferredSize(new java.awt.Dimension(160, 40));
        logoutbtn.addActionListener(this::logoutbtnActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(logoutbtn, gridBagConstraints);

        checkticketsBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkticketsBtn.setForeground(new java.awt.Color(102, 0, 102));
        checkticketsBtn.setText("Check Tickets");
        checkticketsBtn.setPreferredSize(new java.awt.Dimension(160, 40));
        checkticketsBtn.addActionListener(this::checkticketsBtnActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(checkticketsBtn, gridBagConstraints);

        jPanel4.add(jPanel5, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butDetailbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDetailbtnActionPerformed
        // TODO add your handling code here:
        new BusDetails().setVisible(true);
        dispose();
    }//GEN-LAST:event_butDetailbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to logout?",
        "Logout",
        JOptionPane.YES_NO_OPTION
        );

        if(choice == JOptionPane.YES_OPTION){
            
            Session.currentAdminId = 0;
            Session.currentUserName = null;
            
            new AdminLogin().setVisible(true);
            dispose();

        }
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void checkticketsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkticketsBtnActionPerformed
        // TODO add your handling code here:
        new UpdateTickets().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_checkticketsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butDetailbtn;
    private javax.swing.JButton checkticketsBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JLabel welcomelbl;
    // End of variables declaration//GEN-END:variables
}
