/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busbookingmanagement.gui.admin;

import busbookingmanagement.dao.BusAdmin;
import busbookingmanagement.dao.BusDAO;
import busbookingmanagement.gui.user.BusList;
import busbookingmanagement.util.Session;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guruv
 */
public class BusDetails extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BusDetails.class.getName());

    /**
     * Creates new form AddBus
     */
    public BusDetails() {
        initComponents();
        loadBusTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        backtoDashbrn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        modifybtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addbusbtn = new javax.swing.JButton();
        delbusbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(695, 70));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome Admin");
        jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

        backtoDashbrn.setBackground(new java.awt.Color(153, 204, 255));
        backtoDashbrn.setFont(new java.awt.Font("Segoe UI", 0, 5)); // NOI18N
        backtoDashbrn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busbookingmanagement/gui/admin/up-arrow_7699468.png"))); // NOI18N
        backtoDashbrn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backtoDashbrn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backtoDashbrn.setMargin(new java.awt.Insets(100, 100, 100, 100));
        backtoDashbrn.setPreferredSize(new java.awt.Dimension(80, 20));
        backtoDashbrn.addActionListener(this::backtoDashbrnActionPerformed);
        jPanel2.add(backtoDashbrn, java.awt.BorderLayout.WEST);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(695, 70));
        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        modifybtn.setText("Modify");

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bus List You can Add Delete or Update");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus ID", "Bus Number", "Bus Name", "From", "To"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        addbusbtn.setText("Add Bus");
        addbusbtn.addActionListener(this::addbusbtnActionPerformed);

        delbusbtn.setText("Delete");
        delbusbtn.addActionListener(this::delbusbtnActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addComponent(addbusbtn)
                .addGap(97, 97, 97)
                .addComponent(delbusbtn)
                .addGap(96, 96, 96)
                .addComponent(modifybtn)
                .addGap(204, 204, 204))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbusbtn)
                    .addComponent(delbusbtn)
                    .addComponent(modifybtn))
                .addGap(27, 27, 27))
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backtoDashbrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoDashbrnActionPerformed
        // TODO add your handling code here:
        new AdminDashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_backtoDashbrnActionPerformed

    private void delbusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbusbtnActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();

        if(row == -1){

            JOptionPane.showMessageDialog(this,"Please select a bus");

            return;

        }
        String busno = (String) jTable1.getValueAt(row,0);
        BusAdmin addao = new BusAdmin();
        
        int confirm = JOptionPane.showConfirmDialog(
        this,
        "Confirm delete this Bus?",
        "Confirm",
        JOptionPane.YES_NO_OPTION
        );

        if(confirm != JOptionPane.YES_OPTION){
            return;
        }
        
        try {
            addao.delBus(busno);
        } catch (ClassNotFoundException ex) {
            System.getLogger(BusDetails.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (SQLException ex) {
            System.getLogger(BusDetails.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        

        JOptionPane.showMessageDialog(this,"Bus Deleted Successfully");
        jTable1.clearSelection();
    }//GEN-LAST:event_delbusbtnActionPerformed

    private void addbusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbusbtnActionPerformed
        // TODO add your handling code here:
        new AddBus().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_addbusbtnActionPerformed

    public void loadBusTable(){

        try{
            BusDAO dao = new BusDAO();
            ResultSet rs = dao.getAllBuses();

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            model.setRowCount(0); // clear old rows

            while(rs.next()){

                Object row[] = new Object[5];

                row[0] = rs.getInt("BusID");
                row[1] = rs.getString("BusNo");
                row[2] = rs.getString("BusName");
                row[3] = rs.getString("Source");
                row[4] = rs.getString("Destination");

                model.addRow(row);

            }

        }catch(Exception e){
            e.printStackTrace();
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BusDetails().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbusbtn;
    private javax.swing.JButton backtoDashbrn;
    private javax.swing.JButton delbusbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modifybtn;
    // End of variables declaration//GEN-END:variables
}
