/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiprojects;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author guruv
 */
public class EmployeeSearchFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmployeeSearchFrame.class.getName());

    /**
     * Creates new form EmployeeSearchFrame
     */
    public EmployeeSearchFrame() {
        
        initComponents();
        fillComboBox();
        setupAutoComplete();
    }
    
    public void fillComboBox() {
        try (Connection con = getConnection();
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery("SELECT EmpName FROM employees")) {

            // Clear existing items and add a default prompt
            jComboBox1.removeAllItems();
            jComboBox1.addItem("- Select Employee -");

            while (rs.next()) {
                jComboBox1.addItem(rs.getString("EmpName"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }
    public Connection getConnection() {
        try {
            // Updated URL for modern MySQL compatibility
            String url = "jdbc:mysql://localhost:3306/EmployeeCRUD?"+"useSSL=false&serverTimezone=UTC";
            return DriverManager.getConnection(url, "root", "Guru@24748");
        } catch (SQLException e) {
            System.out.println("Connection Error: " + e.getMessage());
            return null;
        }
    }
    
    private void setupAutoComplete(){
        jComboBox1.setEditable(true);
        JTextComponent editor = (JTextComponent) jComboBox1.getEditor().getEditorComponent();
        
        editor.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e){
                if(e.getKeyCode() == KeyEvent.VK_ENTER || e.getKeyCode() == KeyEvent.VK_P || e.getKeyCode() == KeyEvent.VK_DOWN){
                    return;
                }
                String text= editor.getText();
                if(text.length()>=2){
                    try {
                        updateComboBoxList(text);
                    } catch (SQLException ex) {
                        System.getLogger(EmployeeSearchFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                    }
                    jComboBox1.setPopupVisible(true);
                    editor.setText(text);
                }
                
            }
        });
    }
    
    private void updateComboBoxList(String search) throws SQLException{
        try(Connection con = getConnection();
                PreparedStatement pst = con.prepareStatement("SELECT EmpName FROM EMPLOYEES"+" WHERE EmpName LIKE ?")){
            pst.setString(1, search+"%");
            ResultSet rs = pst.executeQuery();
            
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            while(rs.next()){
                model.addElement(rs.getString("EmpName"));
            }
            jComboBox1.setModel(model);
            
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    
    private void displayEmployeeDetails(String name) throws SQLException{
        try(Connection con = getConnection()){
            PreparedStatement pst = con.prepareStatement("SELECT * FROM EMPLOYEES WHERE EmpName=?");
            pst.setString(1, name);
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                txtEmpID.setText(rs.getString("Id"));
                txtdept.setText(rs.getString("dept"));
                txtsalary.setText(rs.getString("Salary"));
                txtlocation.setText(rs.getString("location"));
            }
            
        }catch(SQLException e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        txtEmpID = new javax.swing.JTextField();
        txtdept = new javax.swing.JTextField();
        txtsalary = new javax.swing.JTextField();
        txtlocation = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        txtlocation.addActionListener(this::txtlocationActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdept, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(txtEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtlocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlocationActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        Object selected = jComboBox1.getSelectedItem();
        
        if(selected == null || selected.toString().isEmpty()){
            return;
        }
        
        String name = selected.toString();
        try {
            displayEmployeeDetails(name);
        } catch (SQLException ex) {
            System.getLogger(EmployeeSearchFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EmployeeSearchFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField txtEmpID;
    private javax.swing.JTextField txtdept;
    private javax.swing.JTextField txtlocation;
    private javax.swing.JTextField txtsalary;
    // End of variables declaration//GEN-END:variables
}
